#
# This is a flox environment manifest.
# Visit flox.dev/docs/concepts/manifest/
# or see flox-edit(1) for more information
#

[install]
jupyter.pkg-path = "jupyter-all"
pandas.pkg-path = "python311Packages.pandas"
matplotlib.pkg-path = "python311Packages.matplotlib"
numpy.pkg-path = "python311Packages.numpy"
seaborn.pkg-path = "python311Packages.seaborn"
pyarrow.pkg-path = "python311Packages.pyarrow"
sympy.pkg-path = "python311Packages.sympy"
pydot.pkg-path = "python311Packages.pydot"
plotly.pkg-path = "python311Packages.plotly"
folium.pkg-path = "python311Packages.folium"
statsmodels.pkg-path = "python311Packages.statsmodels"
pycrypto.pkg-path = "python311Packages.pycrypto"
keras.pkg-path = "python311Packages.keras"
tensorflow-bin.pkg-path = "python311Packages.tensorflow-bin"
bokeh.pkg-path = "python311Packages.bokeh"
ftfy.pkg-path = "python311Packages.ftfy"
xmltodict.pkg-path = "python311Packages.xmltodict"
biopython.pkg-path = "python311Packages.biopython"
scikit-learn.pkg-path = "python311Packages.scikit-learn"
scikit-fuzzy.pkg-path = "python311Packages.scikit-fuzzy"
scikit-image.pkg-path = "python311Packages.scikit-image"
scikit-misc.pkg-path = "python311Packages.scikit-misc"

[vars]
virtualEnv='./nb-venv/'

[hook]
script = """
        if [[ -d $virtualEnv ]]; then
       		echo; echo -n "⚡️ Activating existing venv in $virtualEnv..."
        	. $virtualEnv/bin/activate
		echo "done."
	fi

	# If we see a requirements.txt file, install its contents
	# into a virtual environment

        if [[ -f requirements.txt ]]; then
		echo -n "🐍 Processing requirements.txt..."
        	[ ! -d $virtualEnv ] && python -m venv $virtualEnv
        	. $virtualEnv/bin/activate
        	pip3 -qq install -r requirements.txt
		echo "done."
	fi

	# Set an alias to start the notebook and educate the user

	alias nb="jupyter notebook --ip 0.0.0.0"
        echo; echo "Jupyter environment ready - start notebook with alias 'nb'."

"""

[options]
systems = ["x86_64-linux", "aarch64-darwin"]
